# Generated by Django 4.2.16 on 2024-10-19 03:05

from django.db import migrations, models
from django.db import connection

def create_hypertable(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT create_hypertable('aapl_stock_data', 'time', if_not_exists => TRUE);
        """)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AaplStockData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'db_table': 'aapl_stock_data',
            },
        ),
        migrations.RunPython(create_hypertable),
    ]
