# Generated by Django 4.2.16 on 2024-10-19 03:20

from django.db import migrations, models
from django.db import connection

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaplstockdata',
            old_name='timestamp',
            new_name='time',
        ),
        
        migrations.RunSQL(
            """
            SELECT create_hypertable('aapl_stock_data', 'time');
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS aapl_stock_data CASCADE;
            """,
        ),
    ]
