# Generated by Django 4.2.16 on 2024-10-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaplstockdata',
            old_name='timestamp',
            new_name='time',
        ),
    ]
